---
- name: Get control plane join command.
  shell: 
    cmd: "echo \"{{ kubernetes_join_command.replace('\n', '') }} --control-plane --certificate-key $(kubeadm init phase upload-certs --upload-certs 2>/dev/null | grep -vw -e certificate -e Namespace)\""
  when: inventory_hostname == init_node
  register: kubernetes_control_join_command_result

- name: Set the kubeadm control join command globally.
  set_fact:
    kubernetes_control_join_command: >
      {{ kubernetes_control_join_command_result.stdout }}
      {{ kubernetes_control_join_command_extra_opts }}
  when: kubernetes_control_join_command_result.stdout is defined and inventory_hostname == init_node
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: DEBUG - print control plane join command
  debug:
    msg: Join command:- {{ kubernetes_control_join_command }}
  when: not inventory_hostname == init_node

- name: Join additional control plane nodes.
  shell: >
    {{ kubernetes_control_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']
  when: not inventory_hostname == init_node

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755
  when: not inventory_hostname == init_node

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644
  when: not inventory_hostname == init_node
